### ISSUE TITLE
Vanilla statistics working intermittently

### ISSUE THREAD

**Issue by pire** [vanilla/vanilla#1810] opened 2014-03-26 09:44 UTC
About 70% of the time the statistics graph in the _/dashboard/settings_ fails to load.
Instead we get a "**Permission denied - Token Verification is required, but failed.**".

The same happens with the _/dashboard/statistics_ where ~70% of the time it says "**Problem with credentials.**", even when they've been re-registered.

After looking a bit into the code I saw that the **SecurityToken** sent to _http://analytics.vanillaforums.com/graph/_ is blank whenever it fails.

Vanilla version is **2.2.3.4**.

**Comment by linc** [comment] 2015-02-14 16:37
Needs Tim input; I have another report about this too. Basically we need a way for end users to resolve this.

**Comment by raykai** [comment] 2016-02-24 07:20
im having the same prob

**Comment by linc** [comment] 2016-08-24 23:53
What we really need here is someone who can reliably reproduce the issue to really dig in an figure out where this is breaking down. 

* There is a `SecurityToken` required. Is it sent with your final request?
* Is the `SecurityToken` input field in the dashboard's source set?
* Is the call to `graph/getsecuritytoken.json` to get the token in the first place succeeding?

I've taken a fresh look at this code and don't see anything obviously wrong with its logic that could cause it to intermittently fail. I don't see a path forward here without more information about it.

**Comment by pire** [comment] 2016-09-07 14:30
Hi @linc I did a dirty, **dirty** hack a long time ago. I can't remember my train of though, but maybe it helps?

I edited `/plugins/VanillaStats/views/dashboard.php`.

Under line 8. 
```php 
$SecurityToken = $this->Data['SecurityToken'];
```

I added the following

```php
$file = '/path/to/my/new/cacheToken.php';

if( !is_null($SecurityToken) ) {
  // security token is not null. Lets cache it for when it is
  $myfile = fopen($file, "w");
  $content = '<?php $SecurityToken = ' . "'$SecurityToken';";
  fwrite($myfile, $content);
  fclose($myfile);
} else {
  // token is null, use the cache and hope it's still a valid token
  require_once($file);
}
```

Unsure if that helps, but it has kept the stats running for the last couple of years on my client's site!

**Comment by DaazKu** [comment] 2016-10-25 16:04
SecurityToken does not exist anymore since https://github.com/vanilla/vanilla/pull/4116
The issue is also super old.

@raykai @pire Could you try with the new version and tell me if there is still an issue?

Unless it can still be reproduced on the new version I would close this.

**Comment by pire** [comment] 2016-10-26 08:46
Thanks, @DaazKu .

Unfortunately I don't run that project anymore (it *has* been a long time!) so I can't update it.
I know it's still working well with the dirty hack though.

Happy if you close it to clear up issues.

**Closed** 2016-10-28 14:57 UTC
Labels: Awaiting Feedback
