### ISSUE TITLE
Installation: Invalid default value for 'DateExpires'

### ISSUE THREAD

**Issue by biozahard** [vanilla/vanilla#6011] opened 2017-10-05 12:05 UTC
![image](https://user-images.githubusercontent.com/5406151/31226385-98295de2-a9de-11e7-88b6-be9f73e28f18.png)

**Comment by linc** [comment] 2017-12-26 22:31
Duplicate of https://github.com/vanilla/vanilla/issues/5832

You need to turn off Strict Mode in MySQL, unfortunately.

**Closed by linc** 2017-12-26 22:31 UTC
