### ISSUE TITLE
Utility Structure bug?

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#2784] opened 2015-05-30 04:13 UTC
I upgraded to latest master (Version 2.2.100.1) and even after repeatedly running /utility/structure/ I see:

`update GDN_Role `Role`
set Type = 'applicant'
where RoleID = '4';

update GDN_Role `Role`
set Type = 'member'
where RoleID = '8';

update GDN_Role `Role`
set Type = 'unconfirmed'
where RoleID = '3';

update GDN_User `User`
set Permissions = ''
where Permissions <> '';

update GDN_UserAuthenticationProvider `UserAuthenticationProvider`
set AuthenticationSchemeAlias = 'GooglePlus'
where AuthenticationSchemeAlias = 'Google+';`

Shouldn't these stop showing up on rescan after being run and changes are made to the DB?

**Comment by linc** [comment] 2015-08-31 03:05
Duplicate of #2407

**Closed by linc** 2015-08-31 03:05 UTC
