### ISSUE TITLE
Rich Editor: Linking to a Vanilla comment previews first comment in page instead of the one linked

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#9373] opened 2019-10-05 18:02 UTC
When linking directly to a comment in Vanilla, the preview description is selected from the first comment on the page rather than the one linked. It would make the intention much clearer to quote the correct comment.

**Comment by charrondev** [comment] 2019-10-07 15:10
I think there's 2 pieces here:

1. `CommentEmbedFactory` doesn't seem to be matching some particular URL scheme. As a result it the fallback site scraping is being used. This would the preview to be scraped from the sign in page on private communities.
2. Our `DiscussionsController` doesn't seem to be properly setting meta descriptions for pages with an explicit comment URL. This affects things other than our rich embeds (like previews in Slack, FB, Twitter, google, etc).

**Comment by charrondev** [comment] 2020-01-14 04:04
This is no longer reproducible on the latest releases. The comment embed was broken previously due to some updates to make it work with subcommunities (at which point it worked only with subcommunities), which caused it to _only_ match when subcommunities were active.

It was fixed with https://github.com/vanilla/vanilla/pull/9550

**Closed by charrondev** 2020-01-14 04:04 UTC
Labels: Domain: Rich Editor, Status: PR, Type: Enhancement
