### ISSUE TITLE
Rich Editor - Odd error

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#7579] opened 2018-08-09 02:19 UTC
I encountered a very odd error that saw the entire editor disappear from the page which I think means it "crashed". I'm not sure exactly what I did, but I was editing some copy/pasted HTML and hit delete.

Here is a stack trace I saw in my console:

```
lib-dashboard-app.min.js:77 Uncaught DOMException: Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (0).
    at e.value (http://dev.vanilla.localhost/plugins/rich-editor/js/app/rich-editor-app.min.js?h=57210c89:72:29826)
    at e.value (http://dev.vanilla.localhost/plugins/rich-editor/js/app/rich-editor-app.min.js?h=57210c89:8:29765)
    at t.get [as pilcrowStyles] (http://dev.vanilla.localhost/plugins/rich-editor/js/app/rich-editor-app.min.js?h=57210c89:52:16245)
    at t.render (http://dev.vanilla.localhost/plugins/rich-editor/js/app/rich-editor-app.min.js?h=57210c89:52:14769)
    at Ci (http://dev.vanilla.localhost/applications/dashboard/js/app/lib-dashboard-app.min.js?h=57210c89:77:62179)
    at http://dev.vanilla.localhost/applications/dashboard/js/app/lib-dashboard-app.min.js?h=57210c89:77:73951
    at cu (http://dev.vanilla.localhost/applications/dashboard/js/app/lib-dashboard-app.min.js?h=57210c89:77:76676)
    at lu (http://dev.vanilla.localhost/applications/dashboard/js/app/lib-dashboard-app.min.js?h=57210c89:77:76981)
    at Bu (http://dev.vanilla.localhost/applications/dashboard/js/app/lib-dashboard-app.min.js?h=57210c89:77:80306)
    at Fu (http://dev.vanilla.localhost/applications/dashboard/js/app/lib-dashboard-app.min.js?h=57210c89:77:79879)
```

I apologize if this isn't much to go on and you can close this issue if it's not enough, but perhaps you can see a division by zero type error in the code somewhere or something like that. The INT_MAX seems to point to funny arithmetic. If not I'd close this issue.

**Comment by charrondev** [comment] 2019-01-28 03:59
I'm going to close this out because there's really no way to reproduce. The issue can still be referenced even if it's closed if this happens again.

My feeling is this was likely resolved with the code-block pasting issues though.

**Closed by charrondev** 2019-01-28 03:59 UTC
