### ISSUE TITLE
Dashboard v3: Warnings & Notes addon

### ISSUE THREAD

**Issue by JulieVanilla** [vanilla/vanilla#4529] opened 2016-09-23 16:37 UTC
With Dashboard v3, the Warnings & Notes addon now has a settings button you can click on. Previously, there were no settings available.

Clicking on the settings brings up a largely unstyled popup that allows the admin to add a new warning if they so choose (points to siteurl/warningtypes/add):

![screen shot 2016-09-23 at 12 26 34 pm](https://cloud.githubusercontent.com/assets/8974997/18793743/2986fb92-818a-11e6-90d5-c687d51db13a.png)

While this feature would be welcomed by the clients, I'm unsure if this is an intended feature, particularly as it is not properly styled and it didn't exist in the previous incarnation of the dashboard.

**Comment by DaazKu** [comment] 2016-09-23 16:42
Duplicate of https://github.com/vanilla/internal/issues/670

**Closed by DaazKu** 2016-09-23 16:42 UTC

**Comment by JulieVanilla** [comment] 2016-09-23 16:43
Not an exact duplicate -- this functionality did not exist beforehand. Is this functionality for the Warnings & Notes addon intended?

**Comment by DaazKu** [comment] 2016-09-23 16:46
The setting button land you to the same page than the link in the left nav.
The functionality did exist beforehand.

All there is to do if fix the plugin/styling for the dashboard v3. (Which the other issue is all about)

**Comment by JulieVanilla** [comment] 2016-09-23 16:51
The Warnings & Notes addon has never had a settings page that was available to the admins until the new Dashboard. I have confirmed by visiting sites on private clusters that are on the 1607 release that have the Warnings & Notes addon enabled. There's no setting option for it either in Browse Addons, nor in the left-hand column. Nor does the /warningtypes/add page exist on those sites. Was this functionality recently added and it just coincides with the new dashboard?

**Comment by DaazKu** [comment] 2016-09-23 17:02
Yes. I linked the PR in the previous post.
