### ISSUE TITLE
Bold text rendering issue with rich editor

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#9941] opened 2020-01-16 04:38 UTC
**Describe the bug**
Bold text renders differently in the server than the editor when combined with an emoji and a list.

**To Reproduce**
1. Make a list with the first line ending in an emoji.
2. Make the list bold.
3. Add non-bold text after list.
4. Save the post.
5. See the non-bold text renders as bold.

Use this JSON:

```json
[
    { "insert": "Great, Thank you, " },
    { "insert": { "mention": { "name": "charrondev", "userID": 63709 } } },
    { "insert": " " },
    { "insert": { "emoji": { "emojiChar": "😘" } } },
    { "insert": { "emoji": { "emojiChar": "👍️" } } },
    { "insert": "\n" },
    { "attributes": { "bold": true }, "insert": "I`ll file the 1st issue to Github.. " },
    { "attributes": { "bold": true }, "insert": { "emoji": { "emojiChar": "👍️" } } },
    { "attributes": { "list": { "depth": 0, "type": "ordered" } }, "insert": "\n" },
    { "attributes": { "bold": true }, "insert": " Emojis" },
    { "attributes": { "list": { "depth": 0, "type": "ordered" } }, "insert": "\n" },
    {
        "insert": "Aside of Users having the same Problem as RJ (everybody expects the same User experience as on PC and are searching for the Emoji List Button.. "
    },
    { "insert": { "emoji": { "emojiChar": "😃" } } },
    { "insert": "):\nWe have something like \"Customized\"  Emojis, that everybody got used to it... \n" }
]
```

**Expected behavior**
Non-bold text renders as bold.

**Comment by ldom66** [comment] 2020-08-27 14:23
Duplicate of vanilla/vanilla#10802

**Closed** 2020-08-27 17:52 UTC
Labels: Domain: Format Service, Type: Bug
