### ISSUE TITLE
Can't delete inserted rich quotes on mobile/sometimes desktop; backspace defocuses field

### ISSUE THREAD

**Issue by michaeltyson** [vanilla/vanilla#8425] opened 2019-02-20 04:16 UTC
**Describe the bug**

On mobile devices, rich quotes cause a severe editing issue: after inserting a rich quote, it cannot be deleted. If one backspaces from the line immediately following the quote, the entire text field defocuses. 

If the quote is more than a line or two, then it's impossible to focus the text field, as tapping the quote (which is now all that is visible within the text field, with no following whitespace). 

If one does find some whitespace to tap in, the keyboard reappears but text cannot be inserted. 

One must reload the page to continue editing, probably losing the text field contents, if draft hasn't been saved. If draft *has* been saved with the quote intact, the issue remains - one must either delete the draft and start over, or post with the unwanted quote.

A similar effect can be observed on the desktop if two quotes are inserted.

**Vanilla info**

2.8, using Keystone theme and rich editor.

**To Reproduce**

1. On a mobile device (tested on Safari), tap quote for a post, then in the text field press backspace.
2. Keyboard vanishes
3. Tap in text field below quote (if possible), and type

Or on desktop:

1. Insert two quotes (tap quote for one post, then for another)
2. Click in the text field below the quotes, and press backspace
3. Field defocuses
4. Click back in text field, and try to type (nothing happens)

**Expected behavior**
Backspace immediately before quote should erase it, without defocusing the text field.

**Screenshots**
See iOS screen recording: http://ds.michael.tyson.id.au/1550635494/ScreenRecording_02-20-2019-15-03-53.MP4
And Mac: http://ds.michael.tyson.id.au/1550635839 (not visible, but furiously typing from 0:10)

**Additional context**
This seems to be related to #5860, which appears to have been closed as won't-fix - I beg you to reconsider, as this makes rich quotes very problematic on mobile devices, which is the vast majority of our users.

**Comment by charrondev** [comment] 2019-02-20 05:12
Not quite the same as https://github.com/vanilla/vanilla/issues/5860 although they are both keyboard traps. I'm 100% interesting in resolving keyboard traps like this in Rich Editor (we've already put quite a lot of work into it). The equivalent to that issue would be a normal quote.

This issue affects all embeds actually. The issue is we place real focus on them. This is ideal for desktop usage and users with screenreader but has this side effect on mobile.

I feel fixing the following issues would likely eliminate this trap:

- https://github.com/vanilla/vanilla/issues/7861
- https://github.com/vanilla/vanilla/issues/7597

**Closed** 2020-01-21 22:52 UTC
Labels: Domain: Rich Editor, Type: Bug
