### ISSUE TITLE
Pasting Excel or Word table into a post causes problems

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#6076] opened 2017-10-27 18:24 UTC
# Issue

When copying a table from Excel or Word and pasting into a post, the result is a table text + an image

# To Reproduce

Copy a table from excel or word (it has to be a desktop application and not Gmail Sheet) paste it into a post

## Note

MarkDown BBCode, HTML, result as mentioned above
Text, TextEx, WYSIWYG the table is added as an attachement

**Comment by vrjrobitaille** [comment] 2017-10-27 18:52
To add a quick note here. 

WYSIWYG, the table isn't added as an image at all.

**Comment by vrjrobitaille** [comment] 2017-10-27 20:33
Upon further testing, I've discovered that any specially formatted text in Word, or Excel will essentially paste an image into a post. The image itself isn't a problem. The problem arises when the text AND the image is added to a post.

**Comment by LauraMakesArt** [comment] 2017-11-21 00:49
I'd still like for this issue to get some careful consistency with its testing. I feel like we talked about this before, but I wanted to reiterate a few things: 

-Vanilla can upload an image from copy pasting. In your browser if you grab any image using "copy image" vanilla will "generate a CDN link"/upload the picture to our CDN. 

-To my knowledge Vanilla _cant_ take something that's text based and convert it into an image, at all. That means the image data always has to be also attached to the clipboard at the time for a link to be created for an uploaded image. 

-All of the office suite has Copy-As-Image functionality, which is why this would be isolated to the windows software. If we were converting tables to images, it would happen when we copied them from elsewhere. 

We cant stop office from adding image data to the clipboard, and vanilla _cant_ create an image from nothing, so it has to be in the clipboard data. The only way I can see this being an error on our end is if Vanilla is occasionally ignoring an image, but office _always_ attaches the image to the clip board.  I could see maybe a combination of text/images in clipboards maybe causing inconsistencies? 

@linc perhaps I'm wrong about vanilla and we have some hidden image encoding in the editor I'm unaware of.

**Comment by linc** [comment] 2017-12-26 22:38
We've never support pasting Excel or Word into a Vanilla post perfectly. We decided this when we dropped the feature along with cleditor years ago. Doing this requires a special "Paste from Word" option in the past, which folks pasting from Word *didn't know to use* thereby making it perfectly useless. In my opinion, the change here should be to aggressively strip the stuff we don't want being pasted, not attempting to properly render / translate it.

**Comment by linc** [comment] 2017-12-26 22:40
I bet this is the issue we recently saw with base64 image data being pasted into a discussion that causes the page to become inaccessible on cloud. We never did narrow down a reproducible way of doing this, or exactly what the problem was. We should connect that issue if it was filed; I'm not able to find it currently.

**Comment by charrondev** [comment] 2019-02-06 22:24
Fixed in Rich Editor which is the default editor as of 2.8.

Rich editor does aggressively strip and normalize pasted input.

**Closed** 2019-02-06 22:30 UTC
Labels: Design Limitation, Domain: Advanced Editor, Status: Won't Fix, Type: Bug
