### ISSUE TITLE
2.6 & 2.5.2 install: Vanilla application not enabled on completion of setup

### ISSUE THREAD

**Issue by whu606** [vanilla/vanilla#7262] opened 2018-05-27 09:42 UTC
Windows/XAMPP

This also occurred with 2.5.

![image](https://user-images.githubusercontent.com/5166805/40584517-e04da964-61aa-11e8-9d01-9e3443aa5fdd.png)

However, enabling any plugin resolves this, as it enables the Vanilla plugin, along with the chosen plugin

Original conf.php following successful installation

$Configuration['EnabledPlugins']['recaptcha'] = true;
$Configuration['EnabledPlugins']['GettingStarted'] = 'GettingStarted';
$Configuration['EnabledPlugins']['stubcontent'] = true;
$Configuration['EnabledPlugins']['swagger-ui'] = true;

Conf.php after enabling plugin (Index photos in this case):

// EnabledPlugins
$Configuration['EnabledPlugins']['recaptcha'] = true;
$Configuration['EnabledPlugins']['GettingStarted'] = 'GettingStarted';
$Configuration['EnabledPlugins']['stubcontent'] = true;
$Configuration['EnabledPlugins']['swagger-ui'] = true;
$Configuration['EnabledPlugins']['Vanilla'] = true;
$Configuration['EnabledPlugins']['IndexPhotos'] = true;

**Comment by charrondev** [comment] 2019-03-05 04:35
I'm actually going to close this in favour of https://github.com/vanilla/vanilla/issues/7263 since I'm 99% these are the same issue. It's going to be the same root cause of both.

**Closed** 2019-03-05 04:36 UTC
