### ISSUE TITLE
Check user permissions before showing Quote button

### ISSUE THREAD

**Issue by nervoustwit** [vanilla/vanilla#4445] opened 2016-09-09 20:58 UTC
Presently the quote button shows up on a discussion even if the user has no permission to comment on the post. We need to add more robust permission check.

https://github.com/vanilla/vanilla/blob/master/plugins/Quotes/class.quotes.plugin.php#L241

**Comment by linc** [comment] 2016-09-12 20:55
dupe of #4442

**Closed by linc** 2016-09-12 20:55 UTC
