### ISSUE TITLE
Rich Editor Flagging Bug

### ISSUE THREAD

**Issue by Krisstoffer** [vanilla/vanilla#8875] opened 2019-05-30 07:28 UTC
**Describe the bug**
I found this bug while reporting a spammer on open.vanilla.... etc basically when reporting an issue with rich content it produces the familiar "error rendering this rich post"

**Vanilla info**
1. I dunno what version you run

**To Reproduce**
Steps to reproduce the behaviour:
1. Find a spammer
2. ~~beat them stupid(er)~~ Politely Flag the issue
3. Get all excited because the bug exists on the developers' site so it proves you are not crazy! 

**Expected behaviour**
Shows post no errors

**Screenshots**
![Screen Shot 2019-05-30 at 15 22 23](https://user-images.githubusercontent.com/700503/58616080-5a94b300-82ef-11e9-9f14-f57c30380d99.png)

**Additional context**
Silliness aside I'm aware the Flag plugin is not a part of the core but is put together by the core team but it does suggest that issues with the Rich editor persist beyond the basic search (which I was told you guys don't use opting to use advanced search powered by a Sphinx backend (or so I'm told (and read)

**Comment by charrondev** [comment] 2019-05-30 17:00
Closing as a duplicate of https://github.com/vanilla/vanilla/issues/7764 I've copied over your screenshot and reproduction steps there.

**Closed by charrondev** 2019-05-30 17:00 UTC
Labels: Domain: Content Rendering, Type: Bug

**Comment by charrondev** [comment] 2019-05-30 22:36
@Krisstoffer There are a bunch of places that do not properly call `Gdn_Format` in lesser trafficked parts of our code. Rich editor's data is a lot more strictly structured, so it's been a matter of tracking these down.
