### ISSUE TITLE
Rich editor: shift+enter for line-break on desktop

### ISSUE THREAD

**Issue by jamesinc** [vanilla/vanilla#9032] opened 2019-07-11 00:13 UTC
I would like the rich editor to support the insertion of linebreaks `<br/>` when the user presses `<Shift>+<Enter>`, similar to how many other WYSIWYG editors function. Currently the only way to break line is to start a new paragraph.

There are many legitimate uses for linebreaks, such as when presenting formatted text, like an address.

**Comment by charrondev** [comment] 2019-07-30 19:09
Even though https://github.com/vanilla/vanilla/issues/9142 is newer, we'll be tracking this issue over there.

Closing as a duplicate of https://github.com/vanilla/vanilla/issues/9142

**Closed by charrondev** 2019-07-30 19:09 UTC
Labels: Domain: Rich Editor, Type: Request
