### ISSUE TITLE
When deleting a parent category, you can orphan its children

### ISSUE THREAD

**Issue by beckyvb** [vanilla/vanilla#4914] opened 2016-12-08 13:47 UTC
If you delete a parent category, its children categories are not deleted, but become inaccessible without a data fix. When deleting a parent category, we should give the user the option to delete all children categories of the parent, or to move children categories elsewhere.

**Comment by DaazKu** [comment] 2016-12-08 15:15
Duplicate of https://github.com/vanilla/vanilla/issues/4858

**Closed by DaazKu** 2016-12-08 15:15 UTC
