### ISSUE TITLE
Discussion count won't update unless dba/counts is run.

### ISSUE THREAD

**Issue by bchan009** [vanilla/vanilla#6450] opened 2018-01-18 07:22 UTC
Vanilla 2.5, fresh install.  I've had this happen on multiple fresh installs.  Discussion counts on the category page don't update when new discussions are created.

Running dba/counts fixes the count, but it has to be run every time a new discussion is posted.  After running it dba/counts shows "100%" with a line struck through it:

http://i48.photobucket.com/albums/f202/bchan009/Opera%20Snapshot_2018-01-18_014946_srk2.com.png

**Comment by Charrondev** [comment] 2018-01-19 19:58
Hmm, I'm unable to reproduce this on new open source install on my development machine. Could we get some additional information to try to reproduce this?

Mainly:
- Installation method.
- OS.
- Database being used.
- Whether or not you are using a cache like memcache?
- What type of category are these discussions being posted in?
- Are the discussions being posted in a category nested a few levels deep?

Additionally if you could enabled debug mode by setting:

```php
$Configuration["Debug"] = true;
```

in your configuration and see if any errors/warnings occur when you post a new discussion.

Lastly if you could check your PHP and MySQL logs to see if there are any errors in them. The `CountDiscussions` column of the GDN_Category table is supposed to be updated whenever you make a new post. Does the number there match the total listed when the page renders?

**Comment by bchan009** [comment] 2018-01-20 01:01
1. Installation Method - Standard installation following documentation
2. OS - Linux server, my machine is Windows 10
3. Database being used - What do you mean?
4. Using cache - Not sure, don't think so.
5. What type of category - I don't have any nested categories.  Homepage > Category > Discussion List.

Turning on debug I get an error right away when posting a new discussion:

===

Parameter 1 to PostCountPlugin::DiscussionController_AuthorInfo_Handler() expected to be a reference, value given

#0 [internal function]: gdn_ErrorHandler(2, 'Parameter 1 to ...', '/home/bchan009/...', 278, Array)
#1 /home/bchan009/public_html/library/Garden/EventManager.php(278): call_user_func_array(Array, Array)
#2 /home/bchan009/public_html/library/core/class.pluginmanager.php(806): Garden\EventManager->fire('discussioncontr...', Object(DiscussionController), Array)
#3 /home/bchan009/public_html/library/core/class.pluginmanager.php(765): Gdn_PluginManager->callEventHandler(Object(DiscussionController), 'DiscussionContr...', 'AuthorInfo', 'handler')
#4 /home/bchan009/public_html/library/core/class.pluggable.php(133): Gdn_PluginManager->callEventHandlers(Object(DiscussionController), 'DiscussionContr...', 'AuthorInfo')
#5 /home/bchan009/public_html/applications/vanilla/views/discussion/discussion.php(48): Gdn_Pluggable->fireEvent('AuthorInfo')
#6 /home/bchan009/public_html/applications/vanilla/views/discussion/index.php(31): include('/home/bchan009/...')
#7 /home/bchan009/public_html/library/core/class.controller.php(707): include('/home/bchan009/...')
#8 /home/bchan009/public_html/library/core/class.controller.php(1270): Gdn_Controller->fetchView('', false, false)
#9 /home/bchan009/public_html/library/core/class.pluggable.php(210): Gdn_Controller->xRender()
#10 /home/bchan009/public_html/applications/vanilla/controllers/class.discussioncontroller.php(278): Gdn_Pluggable->__call('render', Array)
#11 /home/bchan009/public_html/library/core/class.dispatcher.php(832): DiscussionController->index('38', 'this-is-a-test-...', 'p1?new=1')
#12 /home/bchan009/public_html/library/core/class.dispatcher.php(261): Gdn_Dispatcher->dispatchController(Object(Gdn_Request), Array)
#13 /home/bchan009/public_html/index.php(29): Gdn_Dispatcher->dispatch()
#14 {main}

**Comment by charrondev** [comment] 2019-03-05 03:09
@bchan009 Are you able to reproduce this on the latest version of Vanilla (2.8)?

**Comment by charrondev** [comment] 2019-03-05 04:47
I'm wondering if this is a duplicate of https://github.com/vanilla/vanilla/issues/6450

**Comment by bchan009** [comment] 2019-03-06 07:43
Sorry, but I don't use Vanilla anymore so I can't really confirm if this happens on the latest version.

**Comment by charrondev** [comment] 2019-03-06 16:02
Closing in favour of https://github.com/vanilla/vanilla/issues/7231

**Closed by charrondev** 2019-03-06 16:02 UTC
Labels: Missing: Reproduction Steps, Status: Reply Required
