### ISSUE TITLE
Log all bans

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5095] opened 2017-02-01 17:45 UTC
I never want another "whodunnit" support ticket as long as I live. All bans must appear in the moderation logs with a clear explanation of who or what did it.

Account for Edit User -> check 'Banned' -> Save, among others. There are lots of ways to ban someone.

**Comment by DaazKu** [comment] 2017-02-01 18:18
Duplicate of https://github.com/vanilla/vanilla/issues/4518

**Closed by DaazKu** 2017-02-01 18:18 UTC
