### ISSUE TITLE
[MySQL Strict Mode] compliance

### ISSUE THREAD

**Issue by nikoskip** [vanilla/vanilla#5177] opened 2017-02-13 00:05 UTC
Hello,

I have a fresh installation of Vanilla 2.3 running along with MySQL 5.7.17 and I had a lot problems while I was playing with the administrator and the forum. Some actions triggered the error screen of Vanilla and it took me a while until I found that the problem was related with **strict mode** in MySQL.

My version of MySQL by default comes with this sql-mode:

`ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`

So, finally I removed **STRICT_TRANS_TABLES** and for now, all is working as expected. 

I know it could take a lot of work to review the code and find this specific problems, but it would be nice if you guys add this requirement in the `README.md ` file. I found some related posts with the same problem:

- https://github.com/vanilla/vanilla/issues/4117
- https://open.vanillaforums.com/discussion/17730/vanilla-doesnt-work-well-in-mysql-strict-mode

Thanks! 

**UPDATE**

I also had to deactivate **ONLY_FULL_GROUP_BY** to get some core plugins work.

**Comment by Charrondev** [comment] 2017-04-21 18:28
To get everything working I had to disable **STRICT_TRANS_TABLES**, **ONLY_FULL_GROUP_BY**, and **NO_ZERO_DATE**. We should document this in the README.

**Comment by DaazKu** [comment] 2018-06-27 14:22
Please notify Ops when this Epic is closed.

**Comment by pinchies** [comment] 2018-12-02 10:49
Is it not possible for vanilla forum to manually set the desired SQL_mode on a per-session basis?

https://www.digitalocean.com/community/tutorials/how-to-prepare-for-your-mysql-5-7-upgrade

I was recently burned by this, because the "In this discussion" plugin is incompatible with Strict mode.

`PHP Fatal error:  Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'jgaforum_vf1.c.DateInserted' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /home/jgaforum/public_html/library/database/class.database.php on line 421
`
By disabling that plugin, my issue was resolved. The cause is line 35 in vanilla/plugins/VanillaInThisDiscussion/class.inthisdiscussionmodule.php:

 ```
   public function getData($discussionID, $limit = 50) {
        $sQL = Gdn::sql();
        $this->_UserData = $sQL
            ->select('u.UserID, u.Name, u.Photo')
            ->select('c.DateInserted', 'max', 'DateLastActive')
            ->from('User u')
            ->join('Comment c', 'u.UserID = c.InsertUserID')
            ->where('c.DiscussionID', $discussionID)
            ->groupBy('u.UserID, u.Name, u.Photo')
            ->orderBy('c.DateInserted', 'desc')
            ->limit($limit)
            ->get();
    }
```

I'm not sure what the fix for this is.

**Comment by garygreen** [comment] 2019-07-01 22:33
@charrondev  do you happen to know what the current requirements are for the latest Vanilla release in regards to mysql modes? I cannot seem to find any documentation for it and we're experiencing issues with MySQL 8 (I suspect due to strict mode / various flags).

Also is it possible to have Vanilla enable/disable certain mysql modes, without having to change your mysql config? For example if you have multiple apps running on your server, one regards strict one doesnt then that's a bit of a problem. It would be cool if vanilla could set some options as it's booting up/connecting to mysql, bit like Laravel does.

**Comment by charrondev** [comment] 2019-07-08 14:13
I'm not super knowledgeable about DB configuration, but if it's possible to set that while setting up PDO that would definitely be helpful.

@initvector Do you have any idea of the status around this?

**Comment by nottoseethesun** [comment] 2019-10-29 04:12
Lots of shared hosting accounts now require strict mode for MySQL; a user who wants to use Vanilla is out of luck because shared accounts cannot turn off strict mode for just a single user.

**Comment by charrondev** [comment] 2019-11-07 22:45
@nottoseethesun If there is a particular plugin or feature that isn't working in strict mode please file an individual issue around it. We've fixed most strict mode issues and all of our devs develop in strict mode today, but we may have still missed something.

We're closing this issue because we don't currently have anything known and actionable in it. Vanilla should be functioning in strict mode.

**Closed** 2020-03-30 21:33 UTC
Labels: Domain: Database, Epic
