### ISSUE TITLE
Feature request: let user search for emoji

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#8599] opened 2019-03-28 08:54 UTC
The Rich Editor enables users to use "native" emojis but there are a million of emojis available and even to find the rocket (my favorite!) requires scrolling down half of the list.

I would love to be able to simply type "rocket" somehow - either like a mention lookup is done, startet with some special character or in a search box in the emoji popup itself. Please take a look at e.g. [this project](https://github.com/muan/emojilib) for a implementation of a lookup

**Comment by tburry** [comment] 2019-07-23 19:40
Duplicate of #6578.

**Closed** 2019-07-23 19:40 UTC
Labels: Domain: Rich Editor, Type: Request
