### ISSUE TITLE
CSS Hierarchy

### ISSUE THREAD

**Issue by zel777** [vanilla/vanilla#2503] opened 2015-02-17 21:23 UTC
When using a custom theme (I'm using the bootstrap theme), the hierarchy of the css is not in the correct order.

To be able to override the default styles and template styles, the "custom.css" should be the last stylesheet in the order.

The CSS currently goes in this order:
style.css
**custom.css**
custom_cerulean.css

It should go:
style.css
custom_cerulean.css
**custom.css**

Please let me know if there is a way for me to change the order or if there will be an update fixing this issue.

**Comment by linc** [comment] 2015-02-21 15:03
duplicate of #2032

**Closed by linc** 2015-02-21 15:03 UTC
