### ISSUE TITLE
Rich Editor: Cannot delete image in post on mobile

### ISSUE THREAD

**Issue by Bparm** [vanilla/vanilla#8384] opened 2019-02-14 15:40 UTC
I experienced this on my iPhone X (most recent version of iOS). I had returned to a post on mobile that I had already begun drafting on desktop previously. The post contained an image that I had uploaded inline (not an attachment).

I wanted to get rid of the image but I could only delete my text. When trying to click 'back' to erase I would get stuck as if I was selecting the image. This continued for a while and I could not figure out a way to delete the image from my post on mobile. 

To reproduce:
-Post image in a comment/discussion you are creating
-Try to delete it. 
-Clicking bag selects the image but then I appear to have no way of deleting it.

I do wonder if it's just me who is unable to figure out to delete the image but as best as I can tell there's no way.

**Comment by charrondev** [comment] 2019-02-20 05:16
This is very similar to https://github.com/vanilla/vanilla/issues/8425

I'm broadening the scope of this. It's not keystone related, but affects all rich embeds on mobile.

**Comment by andrewdodson** [comment] 2019-06-18 21:53
This has come up a couple times recently in Support meetings.  Is this something that the Support devs might be able to investigate during one of our sprints?  Or is it tied to other things making that difficult?

**Comment by charrondev** [comment] 2019-06-19 14:57
It's R&D work. Needs escalation for a fix.

**Comment by tburry** [comment] 2019-07-30 14:41
Closes https://github.com/vanilla/support/issues/276

**Comment by tburry** [comment] 2020-01-09 16:11
Duplicate of https://github.com/vanilla/vanilla/issues/8548.

**Closed by tburry** 2020-01-09 16:11 UTC
Labels: Domain: Rich Editor, Type: Bug
