### ISSUE TITLE
Rich Editor: paragraph formatting cannot be mixed

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#8451] opened 2019-02-23 11:09 UTC
All paragraph formattings are exclusive: either H2 or H3 or quote or code or spoiler. Therefore you cannot e.g. put code in a spoiler or quote a H2 heading.

**Comment by tburry** [comment] 2019-02-23 19:30
This is by design to keep the content simple, consistent and beautiful. We are following methodology of the modern editors in medium.com, facebook notes, etc. For this reason I'm treating your issue as a request and closing it.

We may implement this kind of feature in the future, but it's not currently on our roadmap.

**Closed** 2019-02-23 19:30 UTC
Labels: Type: Request
