### ISSUE TITLE
Category deletion not providing dropdown

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/vanilla#4720] opened 2016-10-24 19:43 UTC
When deleting a category, it does not seem to provide a dropdown for where to dump the threads. It will let you confirm the deletion without designating a place for them to go, this seems to simply eliminate the threads completely.

**Comment by linc** [comment] 2016-10-24 19:47
duplicate of #4660

**Closed by linc** 2016-10-24 19:47 UTC
