### ISSUE TITLE
Posting Untrusted Domains Links- URL Improperly Parsed with WySiwg Format

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#6161] opened 2017-11-17 23:12 UTC
## Issue

When posting a link that is not part of the "trusted domains list" we get an improperly formated link when WySiwyg format is used

## Class

[class.format.php](https://github.com/vanilla/vanilla/blob/master/library/core/class.format.php#L1198)

![link post](https://user-images.githubusercontent.com/31856281/32972609-3823d210-cbc1-11e7-8bf2-af8e664bf594.png)

![link1](https://user-images.githubusercontent.com/31856281/32972625-4661efa6-cbc1-11e7-8918-18d90367f011.png)

**Comment by linc** [comment] 2017-12-26 22:54
This is a duplicate of https://github.com/vanilla/vanilla/issues/5961

**Closed by linc** 2017-12-26 22:54 UTC
