### ISSUE TITLE
Rich Editor - Multiple Image Upload

### ISSUE THREAD

**Issue by FarhanVanilla** [vanilla/vanilla#8709] opened 2019-04-16 15:39 UTC
**Describe the bug**
Unable to Upload Multiple Images with Rich Editor. 

**To Reproduce**
1. Click on the image upload/attach button on the bottom of the Rich Editor. You'll see that you're unable to select multiple images for the post.
2. Drag and Drop multiple images into the Rich Editor and you'll see that it's only selected the first image of the bunch.

**Expected behavior**
Would like to be able to upload multiple images with either the upload/attach button or via drag and drop. Images should also maintain order once uploaded into the post.

**Comment by charrondev** [comment] 2019-04-16 15:47
For future reference, this type of thing is not a bug. It's a feature request (and might be better served by a different issue template). It's also a duplicate of https://github.com/vanilla/vanilla/issues/6760 which I just updated with part of the user story from here

**Closed by charrondev** 2019-04-16 15:47 UTC
Labels: Type: Request
