### ISSUE TITLE
Categories DisplayAs "Default" value

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#6185] opened 2017-11-23 19:33 UTC
## Issue

When selecting  the DisplayAs option from "Category" "settings/editcategory", you end up with the below

![displayas](https://user-images.githubusercontent.com/31856281/33186750-1463494e-d05a-11e7-8ed8-b826ed48acc1.png)

A client had the option "Discussions" selected, but their GDN_Cateogry.DisplayAs value was ="Default" in their Database.
The client could not select those categories with DisplayAs value=Default when creating a discussion from the Homepage, The DisplayAs value had to be updated to "Discussions" from their db.

Table GDN_Category.DisplayAs Enum Length 'Categories','Discussions','Flat','Heading',**'Default'**

Table structure should be updated to remove the Default value.

## Note

I could not replicate this issue.

**Comment by tburry** [comment] 2017-12-19 22:10
My guess on the cause:

1. You need a legacy category table with displayAs = default.
2. You need subcommunities turned on.
3. Subcommunities sets `Vanilla.Categories.NavDepth` = 1.
4. There was probably a change somewhere that adjusts the category depth for the purposes of the dropdown or something like that.

**Comment by linc** [comment] 2017-12-26 23:30
Duplicate of https://github.com/vanilla/vanilla/issues/3952 but I closed that one instead.

**Comment by initvector** [comment] 2018-03-27 21:18
Looking through the code, the only way I can see this being an issue is if [`CategoryModel::calculateDisplayAs` calculated the type](https://github.com/vanilla/vanilla/blob/ed8f354543967c4bc795c99a59080639a8e936c5/applications/vanilla/models/class.categorymodel.php#L629) as something other than "Discussions". `Gdn_Form::categoryDropDown` then flags the category as disabled.

https://github.com/vanilla/vanilla/blob/ed8f354543967c4bc795c99a59080639a8e936c5/library/core/class.form.php#L564-L566

It appears the user who originally reported this issue is on a site with a "Vanilla.Categories.NavDepth" config of 1. I am assuming the "Default" category was off the root. In this case, Vanilla would guess this is a "Nested" category and not allow discussions to be posted there. If this *is* the case, I believe this is functioning as intended. If this *was not* the case, we need more information before this issue can be properly addressed.

**Comment by initvector** [comment] 2018-03-27 21:19
> Table structure should be updated to remove the Default value.

The "Default" display type for categories was more or less deprecated in response to #4152. The value cannot be removed from the field's enum without risking breaking backwards compatibility.

**Closed** 2018-03-28 19:53 UTC
