### ISSUE TITLE
setUserMeta() cannot handle duplicate value/userid pair

### ISSUE THREAD

**Issue by clementbirkle** [vanilla/vanilla#3394] opened 2015-12-16 13:55 UTC
Hello,

This code create a error 500 if the value exists:
https://github.com/vanilla/vanilla/blob/master/applications/dashboard/models/class.usermetamodel.php#L225

=> Found with the Signature Module

**Comment by bleistivt** [comment] 2018-09-05 17:02
I can not reproduce this issue (`Gdn::cache()->activeEnabled() == false` as this points to the non-cache logic.)

        $m = Gdn::userMetaModel();
        $m->setUserMeta([1, 1, 2], 'test', 'value1');
        trace($m->getUserMeta([1, 1, 2], 'test'));
        $m->setUserMeta([1, 1, 2], 'test', 'value2');
        trace($m->getUserMeta([1, 1, 2], 'test'));
        $m->setUserMeta([1, 1, 2], 'test', null);
        trace($m->getUserMeta([1, 1, 2], 'test'));

^ works as expected.

It's also unlikely that the UserMetaModel is broken in such a fundamental way.
Not really actionable without an error message, in my opinion.

**Comment by charrondev** [comment] 2018-09-05 21:48
Agreed. Closing due to lack of detail.

**Closed by charrondev** 2018-09-05 21:48 UTC
