### ISSUE TITLE
Embedding a KB article gives a 422 on the scrape endpoint

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#9049] opened 2019-07-15 16:26 UTC
**Describe the bug**

I tried embedding a link to a KB article and got a 422 error.

**To Reproduce**

1. Start a new discussion.
2. Paste this link: https://success.vanillaforums.com/kb/articles/80-2019-005
3. Hit enter to trigger auto embed.

**Expected behavior**

The article should embed properly just like a website.

**Screenshots**

![embed-error](https://user-images.githubusercontent.com/97432/61232145-9fd43f00-a6fb-11e9-96cb-3a6a39c62ae8.gif)

Error response:

```json
{
    "message": "Validation Failed",
    "status": 422,
    "errors": [
        {
            "field": "body",
            "code": "missingField",
            "status": 422,
            "message": "body is required."
        }
    ]
}
```

**Additional context**

I'm not sure if this is widespread or just particular URLs.

**Comment by charrondev** [comment] 2019-07-17 17:56
I'm pretty sure this was fixed in the embed refactor. Just to double check before actually sprinting the issue.

**Comment by charrondev** [comment] 2019-07-25 14:59
Confirmed to not be fixed after the embed refactor.

**Comment by cchabilall83** [comment] 2019-07-30 20:01
The issue here is the because some previously published kb articles don't have excerpts.  The description tag of an article page is built with the excerpt and if that's not set, then an empty string is put in it's place.  Link embeds are built using the page description meta tag.  If the content of that is an empty string, the link embed will fail.  

https://github.com/vanilla/knowledge/blob/e6651148a9018d52338802b954a329e771d9a323/plugins/knowledge/Controllers/Pages/ArticlePage.php#L40

**Comment by alex-mtl** [comment] 2019-07-30 20:05
But we still need to fix it on scraper side I think. So if description is  not present or content of the page is absolutely "empty" we still need to generate embed frame I guess. @charrondev ?

**Closed** 2019-08-01 14:37 UTC
Labels: Domain: Rich Editor, Type: Bug
