### ISSUE TITLE
CombineAssets doesn't work with JS?

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/vanilla#4967] opened 2017-01-01 20:02 UTC
I recently set `$Configuration['Garden']['CombineAssets'] = TRUE;` which nicely combined most of the CSS my forum uses into a single file. However this doesn't seem to do anything for JS; in the source, I see:

```html
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js?v=2.3" type="text/javascript"></script>
  <script src="/forum/js/library/jquery.form.js?v=2.3" type="text/javascript"></script>
  <script src="/forum/js/library/jquery.popup.js?v=2.3" type="text/javascript"></script>
  <script src="/forum/js/library/jquery.gardenhandleajaxform.js?v=2.3" type="text/javascript"></script>
  <script src="/forum/js/library/jquery.atwho.js?v=2.3" type="text/javascript"></script>
  <script src="/forum/js/global.js?v=2.3" type="text/javascript"></script>
  <script src="/forum/applications/vanilla/js/discussions.js?v=2.3" type="text/javascript"></script>
```

Vanilla 2.3.

**Comment by linc** [comment] 2017-12-26 17:52
Duplicate of  #3020

**Closed by linc** 2017-12-26 17:52 UTC
