### ISSUE TITLE
Ideas "Active" tag is button/link

### ISSUE THREAD

**Issue by vanilla-dbarbier** [vanilla/vanilla#10175] opened 2020-03-06 21:52 UTC
**Describe the bug**
When adding an Idea(Ideation), there is an “Active” tag that is added to the thread listing. That tag, is a link that refers to page (https://dev.vanilla.localhost/discussions/tagged/Active). The other tags do not have link on them.

**Vanilla info**
1. Are you sure this is a core Vanilla problem and not caused by any addon you are using? **Yes**
2. Did you follow our generic troubleshooting steps already? **Good question. I'd say yes but I'm not sure where to find that documentation**
3. What Vanilla version are you using? **Version 4.0-2020.004-SNAPSHOT**
4. When did the issue start? **Saw it when I first started using the platform**

**To Reproduce**
When adding an Idea(Ideation), there is an “Active” tag that is added to the thread listing. That tag, is a link that refers to page (https://dev.vanilla.localhost/discussions/tagged/Active). The other tags do not have link on them.
Bug trace:
-/vanilla/plugins/ideation/class.ideation.plugin.php, line.2084.
-/vanilla/plugins/ideation/class.ideation.plugin.php, line.662. (from what I gathered, in the other plugins it’s that method that return the tag’s html).

**Expected behavior**
"Active" should likely not be clickable.

**Screenshots**
![image](https://user-images.githubusercontent.com/61435952/76125146-2d85d700-5fca-11ea-9873-d3477dd60590.png)

**Additional context**

**Comment by vrjrobitaille** [comment] 2020-05-05 12:18
@vanilla-dbarbier Thanks for submitting issues, it's great to know we have so many eyes out there.

This actually  is not a bug, if i'm understanding your  report correctly. Each Idea that is submitted  has a status assigned to it. The  "Active" tag is the default tag that gets added to any new idea that's posted, but as an Admin I can change that any time by going to the Cogwheel and selecting "Edit Idea Status"

All Idea Statuses are clickable, this is a quick way to access the filtered view of your idea category. You'll get to thee same pages by using the Status filter on your idea category's page -
![LaPKzFKyKd](https://user-images.githubusercontent.com/18470831/81065177-02741280-8ea9-11ea-9453-3f65d41e03c9.gif)

We currently don't have the same behaviour for Q&A posts unfortunately, even though they work similarly with tags/statuses. Something I hope we can do in the near future. 

Let me know if you have any questions!

**Comment by vrjrobitaille** [comment] 2020-05-05 12:20
Here's our docs by the way - https://success.vanillaforums.com/kb/articles/92-ideation If you find there are any questions you have that aren't answered here, please do let me know and we can add this to  our backlog of docs that need updating.

**Closed** 2020-05-05 12:20 UTC

**Comment by vrjrobitaille** [comment] 2020-05-05 12:37
I promise I'm done spamming this ticket in just a second. Last thing - if you're curious, take a look at our Product Ideas category on our customer community - https://success.vanillaforums.com/categories/product-ideas

**Comment by vanilla-dbarbier** [comment] 2020-05-05 15:48
Thanks for the clarifications & documentations @vrjrobitaille. There is much to learn about the platform & this is much appreciated.
