### ISSUE TITLE
Rich Editor: Images are left justified rather than centered when embedded in post

### ISSUE THREAD

**Issue by Bparm** [vanilla/vanilla#9657] opened 2019-11-19 15:01 UTC
Previously, an image that was added to a post would be centred with the other types of embeds. However, the past couple of months at least I've noticed that they always appear to be aligned to the left.

I am not sure if this is intentional or not but it definitely changed and then it definitely does not line up with the other embeds.

it also appears to change after posting which doesn't reflect our statement that its a true WYSIWYG experience and the lack of a preview button.

Ex:
Pre posting:
![Screen Shot 2019-11-19 at 9 57 10 AM](https://user-images.githubusercontent.com/24961134/69157683-4a49dd80-0ab3-11ea-8ff3-4a3fd9630e35.png)

After posting:
![Screen Shot 2019-11-19 at 9 57 21 AM](https://user-images.githubusercontent.com/24961134/69157698-52a21880-0ab3-11ea-98e1-3939862aec02.png)

Link to my test site: https://brendan.vanillademo.com/discussion/242/test-image-upload

Steps to reproduce:
Embed an image in a post using the Rich editor. 
-Observe that is set to the left of the post.

Expectation:
It would remain centred as it does before posting.

**Comment by charrondev** [comment] 2019-11-19 15:51
Duplicate of https://github.com/vanilla/support/issues/830

Our image visual sizing behaviour will be changing a lot in `2019.018`, see the discussion at the bottom of the issue.

**Closed by charrondev** 2019-11-19 15:51 UTC
