### ISSUE TITLE
Rich Editor - Final MVP QA

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#7162] opened 2018-05-02 17:34 UTC
The Rich Editor plugin has been enabled and deployed on all of the cl10012. I currently have things configured and setup on my test site https://adamc.vanillawip.com/ but it's easy enough to turn on your own site.

Just navigate to the plugins page and turn on the plugin `Rich Editor (WIP)`.

## Objectives

There a few things in particular that we are testing for and a few things to keep in mind during the testing process.

__Please report all issues on this thread, and not in new separate issues__. There are already quite a few things that have been noted and I will triage this thread after so we don't end up with a bunch of duplicates. 

- _Most_ differences between what you see in the editor and what you see in the final output and what you see in live editor __are a bug__. Please report any inconsistencies here.
- Please report and behaviour that feels buggy or broken.
- If something is confusing or not clear how to do, please report it here.
- Issues with the appearance should be noted as well, but keep in mind some changes will have to be done on a theme by theme basis. https://github.com/vanilla/vanilla/issues/6732

## Template

Please use this template to write up an issue in this thread.

```md
### Description



### Issue severity

<!---
Details about of how critical of an issue this seems to you can help assess priority of bugs and minor feature requests.
-->

### Steps to reproduce

1.
2.
3.

### Screenshot (if applicable)



```

**Comment by DaazKu** [comment] 2018-07-17 18:18
Too late https://github.com/vanilla/vanilla/issues/7474

**Comment by charrondev** [comment] 2018-07-17 19:15
### Description

The editor is showing this paragraph menu on mobile themes. It is supposed to be hidden.

### Issue severity

Medium


### Steps to reproduce

1. Open a discussion on a device with a small viewport and a mobile theme enabled
2. Observe the extra paragraph menu.

### Screenshot (if applicable)

![image](https://user-images.githubusercontent.com/1770056/42840214-13abd37a-89d4-11e8-81f9-8d786d0f8bf1.png)

**Comment by Bparm** [comment] 2018-07-17 20:11
Description: Clicking Quote functionality on another post (quote addon I suppose)  breaks the editor

Severity: High I would say

Steps to reproduce: Click quote icon on another comment. Observe.

![screen shot 2018-07-17 at 4 11 17 pm](https://user-images.githubusercontent.com/24961134/42842740-0daa94cc-89dc-11e8-9baf-496835904039.png)

**Comment by charrondev** [comment] 2018-07-17 20:25
There are 2 things to that.

1. This issue https://github.com/vanilla/vanilla/issues/7057 which is in this sprint, will show an error message in the post body when a posts formatting is messed up.
2. The quotes plugin is marked in the addon requirements as a conflicting addon, but doesn't seem to get enforced properly. This will need to be fixed before release due to the Quotes conflict. https://github.com/vanilla/vanilla/issues/6283

@Bparm How significant does not having a quote system like our current one feel to you?

**Comment by Bparm** [comment] 2018-07-17 20:46
@charrondev I foresee many support tickets if clicking quote on a comment did not work at all with the new editor yes. I think it's important.

**Comment by DaazKu** [comment] 2018-07-18 14:00
### Description

Unable to quote a big chunk of text.


### Issue severity

**PITA**

### Steps to reproduce

1. Start a quote from the paragraph menu
2. Try to paste the following:
> I WANT
>
> THIS 
>
> QUOTED
3. You end up with no quote at all.

*You can't select the whole thing and make it a quote either which is frustrating.*

### Notes

To have that quoted you have to click on the first line, make it a quote and then backspace the next line into the quote to reput the line returns AFTER it's been merged.

**Comment by slafleche** [comment] 2018-07-18 17:40
### Description
Spacing issues with editor.

### Issue severity
Minor

### Steps to reproduce
1. Edit existing post

### Screenshot (if applicable)

<img width="845" alt="screen shot 2018-07-18 at 13 38 22" src="https://user-images.githubusercontent.com/19651440/42898062-110628e8-8a90-11e8-95ba-55ce126a06e6.png">

**Comment by slafleche** [comment] 2018-07-18 17:41
### Description
Spacing issues in new groups

### Issue severity
Minor

### Steps to reproduce
1. Create new group 

### Screenshot (if applicable)

<img width="787" alt="screen shot 2018-07-18 at 13 40 39" src="https://user-images.githubusercontent.com/19651440/42898113-3942adae-8a90-11e8-9a4c-a62fc9b92fbb.png">

**Comment by charrondev** [comment] 2018-07-19 20:14
### Description

Facebook doesn't recognize our User Agent header (I'm sure other sites don't either). We should be using a user agent header that will get sites to give us the same thing other do.


### Issue severity

Low



### Steps to reproduce

1. Try to embed a public facebook link.

### Screenshot (if applicable)

![image](https://user-images.githubusercontent.com/1770056/42967556-9ff41f04-8b6e-11e8-836e-34e9ecd442a4.png)

**Comment by slafleche** [comment] 2018-07-23 13:31
Deflector's heading styles (and probably other themes) clashing with editor.

<img width="852" alt="screen shot 2018-07-23 at 09 21 16" src="https://user-images.githubusercontent.com/19651440/43079434-1c268dde-8e5b-11e8-8fcf-794ffc71185f.png">

**Comment by slafleche** [comment] 2018-07-23 13:36
No validation on links at all. When I insert a bad link on the staff forum and clicked, I got the url: https://staff.vanillaforums.com/discussion/404/badlink. We probably don't want to allow relative links.

We should handle other types of links like e-mails ("mailto:") and phone numbers "tel:".

**Comment by slafleche** [comment] 2018-07-23 13:39
Description
Focus not getting reset

Issue severity
Minor

Steps to reproduce
1. Write some text
2. Select the text
3. Hit "command + k"
4. Tab to "x" and close
5. Hit "command + k" again

Should bring up menu again, but I think the focus is not in the right spot.

**Comment by slafleche** [comment] 2018-07-23 13:45
Description
Switching to spoiler, when you already had paragraph styles keeps those styles in the spoiler and there's no way to get rid of it.

Issue severity
Moderate

Steps to reproduce
1. Write some text
2. Give it a paragraph style, like code block or heading
3. Make it a spoiler

The spoiler wraps the block styles and there's no way to undo it. Clicking another style in the menu remove the spoiler.

**Comment by slafleche** [comment] 2018-07-23 13:49
Is it a conscious decision that all inline styles work in headings except for code? If so, I think it would make more sense to disable the code when you're in a header since it behaves differently than the rest.

**Comment by slafleche** [comment] 2018-07-23 13:54
Description

Unable to switch from quote to code block

Issue severity
Low

Steps to reproduce

1. Make quote
2. Try switching it to code block

We get a plain paragraph, not a code block.

**Comment by tburry** [comment] 2018-07-23 16:15
## List formatting cleared when I use inline code formatting.

Steps to reproduce.

1. Create a numbered list.
2. Select text within the list and choose the inline code formatting.
3. The list formatting disappears around the item you chose.

**Comment by tburry** [comment] 2018-07-23 16:16
## Switch H1, H2 buttons to H2, H3

This is just an icon change. I think we should make the buttons reflect the content rather than being cute for novice users.

**Comment by charrondev** [comment] 2018-07-23 16:19
### Description

Inline menu conflicts with device copy/paste menu for devices with inline copy/paste menus (eg. iOS/windows in touch mode).

### Issue severity

Medium to High

### Steps to reproduce

1. Use the editor on an iPad (I'm unsure if this applies to windows touchscreen devices).
2. Make a text selection
3. Observe the overlapping copy/paste and inline formatting menus.

### Screenshot (if applicable)

![image](https://user-images.githubusercontent.com/1770056/43089334-5acf3cc2-8e72-11e8-8282-fc49b0fe83d5.png)

**Comment by tburry** [comment] 2018-07-23 16:48
## Selected text should always show the inline formatting menu

When I have a text selection (in one paragraph?) then the inline formatting menu should always be open. It should not close when I select a format.

### Steps to reproduce

1. Select some text.
2. Select bold.
3. Notice the menu closes, even though the text is still selected. It should instead remain open.

**Comment by tburry** [comment] 2018-07-23 17:33
## Page up/down in emoji list jumps around

**Priority:** low

### Steps to reproduce

1. Open the emoji editor.
2. Hit tab to make sure your cursor is in the editor.
3. Page up/down with cmd-up or cmd-down.
4. The cursor jumps to a different column each time.

I'm okay leaving this one, but if it's possible to make the cursor jump a multiple of the column count so that it stays in the same column I think that would look better. Only do this if you already coded the page up/down amount and it isn't just built in.

**Comment by tburry** [comment] 2018-07-23 17:37
## Tooltip of Smileys & Faces incorrect

The tooltip on the **Smileys & Faces** tab reads **smileys_people**.

**Comment by tburry** [comment] 2018-07-23 17:40
## Cannot cursor up a row in the Emoji list after paging

**Priority:** medium

### Steps to reproduce

1. Open the emoji list and make sure it has keyboard focus.
2. Page down.
3. Use the cursor keys to go back up. Notice that you can't go back up above the previous row.

**Comment by tburry** [comment] 2018-07-23 18:04
## Emoji list heads don't update

**Priority:** medium

When scrolling through the emoji list the tab highlight updates, but the headings don't.

**Comment by slafleche** [comment] 2018-07-25 13:08
Description

@mentions screw up with selection leaves editor and comes back.

Issue severity
Low

Steps to reproduce

1. Start @mention so we have suggested results
2. Click outside editor (suggestion disappear)
3. Click back to end of @mention (suggestions come back)
4. Hit "enter" we get a new line instead of accepting the selected selection. We instead get a new line and the @mention stays open.

We should complete the @mention instead of inserting a new line.

**Closed** 2018-07-25 21:08 UTC

**Comment by kaecyra** [comment] 2018-07-26 12:42
Fatal error being thrown here https://staff.vanillaforums.com/discussion/417/githubs-hub-tool-is-pretty-great#latest

```
Fatal Error in Vanilla\Formatting\Quill\Blots\HeadingBlot.getHeadingLevel();
```
<img width="1153" alt="screen shot 2018-07-26 at 8 40 06 am" src="https://user-images.githubusercontent.com/248212/43262948-d4411384-90af-11e8-9f99-89cc037b62e0.png">

**Comment by charrondev** [comment] 2018-07-26 14:29
I'm aware of ^

https://github.com/vanilla/vanilla/issues/7522

It has it's own issue. I noticed it last night when I made the post, but was not about to file a detailed issue at midnight.
