### ISSUE TITLE
Advanced Editor flyouts cannot be dismissed with Keystone theme on mobile

### ISSUE THREAD

**Issue by michaeltyson** [vanilla/vanilla#8460] opened 2019-02-27 22:00 UTC
**Describe the bug**
Using the Advanced Editor with the Keystone theme is currently impossible, because the callouts accessed from the toolbar buttons cannot be dismissed on mobile devices: they block the screen and the browser must be reloaded. One can turn off the 'NewFlyouts' feature to make it work again (a bit - there remain severe problems then, too), but this breaks Keystone's navigation.

**Vanilla info**
2.8/Keystone

**Comment by R-J** [comment] 2019-02-28 16:50
I'd say that the problem is the span.mobileFlyoutOverlay (created in flyout.js) which is styled full screen when media query is below 768 but has no trigger to disappear.

If you
- enable the advanced editor and the newflyout setting
- resize your browser below a wifht of 768
- open the smilies dropdown

you see what mobile users experience.

Not sure about the best way to solve that, but my expectation would be that as soon as the main dropdown element looses focus, it should be closed as well as the overlay.

**Comment by R-J** [comment] 2019-02-28 17:19
SImply adding ' $(document).delegate(".mobileFlyoutOverlay", "click", closeAllFlyouts);'  to the top did not work as I expected: the event is fired but that doesn't closes the overlay and the flyout :-(

**Comment by charrondev** [comment] 2019-02-28 17:28
You guys can expect a PR landing today. I'm pretty sure I have the specific issue narrowed down at this point.

**Comment by michaeltyson** [comment] 2019-03-02 06:36
Any updates on this? This is the thing I'm most desperate to fix, because going back to the Advanced Editor will solve most of the problems our community is experiencing.

**Comment by charrondev** [comment] 2019-03-02 06:45
I'm working on it right now, but won't have the sign offs for a PR until Monday. If you need it before then you'll have to temporarily copy the file from the PR.

**Comment by michaeltyson** [comment] 2019-03-02 06:55
Okay, great - and thank you. Yeah, ASAP would be fantastic - happy to do that.

**Comment by charrondev** [comment] 2019-03-02 07:34
@michaeltyson https://github.com/vanilla/vanilla/pull/8475 Pull request here. I've tested it as much as I can. No promises for certain permutations of old iOS devices and WYSIWYG editor (that's always been a pretty terrible experience though), but this should have it as good a shape as I can ever remember it being.

**Comment by michaeltyson** [comment] 2019-03-02 07:35
Thank you very much!

**Comment by michaeltyson** [comment] 2019-03-02 07:40
By the way: any hints on how to encourage the cache busting stuff that appends ?v=2.8 to the js URLs to increment that number?

**Comment by charrondev** [comment] 2019-03-02 08:06
Yeah, we actually don't tend to use those numbers ourselves they have quite a few issues:

- People forget to increment them.
- If you're deployment to multiple app servers on a high traffic site, and the deploy is not instanteous across all app servers you can get the old file caught in an edge node with the new cache key (no grace period).

To fix this set the `Garden.Deployed` config key to a unix timestamp. Our infrastructure does this automatically on deploy, but you could set it to any sufficiently large/random number you want.

If you're interested how it works we have some pretty solid documentation on the class itself https://github.com/vanilla/vanilla/blob/818e6a6dc387dd47a0a9fa78c6899aebf6ba7ecb/library/Vanilla/Web/Asset/DeploymentCacheBuster.php#L10-L33

**Comment by michaeltyson** [comment] 2019-03-02 08:11
Beautiful, thank you! Fix seems to be working just fine, too. Big sighs of relief over here!

**Closed** 2019-03-06 15:37 UTC
Labels: Domain: Advanced Editor, Type: Bug
