### ISSUE TITLE
Categories are not marked "read" when all posts have been viewed

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#4013] opened 2016-05-23 15:32 UTC
If a user views all posts in a category, that category is not being marked as "read".  This ability previously existed in Vanilla and may've been removed, perhaps unintentionally.

I've only come across a couple areas in core Vanilla where the `GDN_UserCategory` table's `DateMarkedRead` column is set.
1. [CategoriesController::markRead](https://github.com/vanilla/vanilla/blob/25e446a817d3af7e11019117b50cbf4991fdaff0/applications/vanilla/controllers/class.categorycontroller.php#L51) - Called when a user clicks "Mark Read" on a category's flyout menu.
2. [CommentModel::setWatch](https://github.com/vanilla/vanilla/blob/d76e3e731b8927bbdd145dd35437ffcfa4743778/applications/vanilla/models/class.commentmodel.php#L559) - Only called if an existing `DateMarkedRead` exists for that user/category.

**Comment by DaazKu** [comment] 2016-08-09 15:51
The mark as read endpoint work as intended.

As for the automated process of setting a category marked as read when you read discussions, it was dropped because of scaling issues.

Putting on hold for the moment.

**Comment by JulieVanilla** [comment] 2016-08-22 21:19
Gonna need more than "dropped because of scaling issues" for clients who are inquiring about this, please.

**Comment by linc** [comment] 2016-08-22 21:47
Needs @tburry input.

**Comment by linc** [comment] 2016-08-30 03:34
See also #2326

**Comment by linc** [comment] 2016-08-30 03:38
See also #2357

**Comment by linc** [comment] 2016-11-14 15:51
This is officially tabled until after API v2 is completed.

The new functionality will also only be when you've read "all" of the most recent ~100 discussions. We're not going to recalculate the entire category.

**Comment by linc** [comment] 2017-12-26 15:30
see also #3900

**Closed** 2019-11-02 17:05 UTC
Labels: Domain: Categories, Status: Won't Fix, Type: Bug
