### ISSUE TITLE
Vanilla 2.2 Bug importer

### ISSUE THREAD

**Issue by Clem01** [vanilla/vanilla#3293] opened 2015-11-17 06:58 UTC
Hello, 

The importer doesn't work with phpBB3 (Undefined variable: Discussions).
The importer is blocked in step 10.

Ps: it work with Vanilla 2.1

Thank you in advance.
![capture d ecran 2015-11-17 a 07 55 12](https://cloud.githubusercontent.com/assets/9021081/11204627/048e73a2-8d01-11e5-91c3-36b0de2cc8d6.png)

**Comment by bleistivt** [comment] 2015-11-17 07:15
Duplicate of #2983

**Closed** 2016-08-30 04:38 UTC
