### ISSUE TITLE
Stub-Content Plugin: Editing user comment on utility update

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#7189] opened 2018-05-09 15:55 UTC
## Details

Stub-Content Plugin was enabled after users posted a few comments. The User comment was edited with the stub content. Ex. [Wow, I didn't know about some of these, thanks! ](https://github.com/vanilla/vanilla/blob/master/plugins/stubcontent/content/comment.yaml#L14)

This was noticed after a utility/update was run
Providing more details in [#29](https://github.com/vanilla/support/issues/29)

**Comment by charrondev** [comment] 2019-03-05 04:25
Since https://github.com/vanilla/support/issues/29 couldn't be reproduced and that issue has more detail than this one, I'm closing in favour of that one. If it can be reproduced and narrowed to an actionable issue, it can be re-opened here.

**Closed by charrondev** 2019-03-05 04:25 UTC
