### ISSUE TITLE
Rich Editor uploading the same image multiple times doesn't work

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#7864] opened 2018-09-26 16:02 UTC
### Details

- Upload an image.
- Delete it
- Upload again (image doesn't appear).

Closes https://github.com/vanilla/support/issues/653

**Comment by charrondev** [comment] 2020-01-09 16:02
Unable to reproduce in the latest versions of Vanilla (2020.001). It was likely fixed in some prior refactoring.

**Closed by charrondev** 2020-01-09 16:02 UTC
Labels: Domain: Rich Editor, Type: Bug
