### ISSUE TITLE
Update pager navigation on ajax updates

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#4783] opened 2016-11-14 15:56 UTC
This can be observed in the spam queue.

Have the spam queue have 2 pages. 
Delete every items on page 1. (This is done using ajax)
You can now go on page 2.

There is nothing to display.

**Comment by charrondev** [comment] 2019-01-04 05:36
Duplicate of https://github.com/vanilla/vanilla/issues/4407. Closing because that one seems to have a bit more detail.

**Closed by charrondev** 2019-01-04 05:36 UTC
